name: integration

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  install-production:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    
    strategy:
      matrix:
        node-version: [14, 16, 18]
        os: [ubuntu-latest, ubuntu-lts]

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Pnpm
        run: |
          npm i -g pnpm
      
      - name: Install Production
        run: |
          pnpm install --prod

      - name: Run server
        run: |
          node integration/integration.test.js &

      - name: Test
        run: |
          bash integration/integration.test.sh

        

